project addfile ../AHB_BusMatrix/AHB_Bus_Matrix_Generator/verilog/built/AHB_BusMatrix/AHB_Arbiter.v
project addfile ../AHB_BusMatrix/AHB_Bus_Matrix_Generator/verilog/built/AHB_BusMatrix/AHB_BusMatrix.v
project addfile ../AHB_BusMatrix/AHB_Bus_Matrix_Generator/verilog/built/AHB_BusMatrix/AHB_BusMatrix_default_slave.v
project addfile ../AHB_BusMatrix/AHB_Bus_Matrix_Generator/verilog/built/AHB_BusMatrix/AHB_BusMatrix_lite.v
project addfile ../AHB_BusMatrix/AHB_Bus_Matrix_Generator/verilog/built/AHB_BusMatrix/AHB_DecoderStageS0.v
project addfile ../AHB_BusMatrix/AHB_Bus_Matrix_Generator/verilog/built/AHB_BusMatrix/AHB_InputStage.v
project addfile ../AHB_BusMatrix/AHB_Bus_Matrix_Generator/verilog/built/AHB_BusMatrix/AHB_OutputStage.v
project addfile ../AHB_BusMatrix/AHB_Bus_Matrix_Generator/verilog/src/cmsdk_ahb_bm_burst_arb.v
project addfile ../AHB_BusMatrix/AHB_Bus_Matrix_Generator/verilog/src/cmsdk_ahb_bm_decode.v
project addfile ../AHB_BusMatrix/AHB_Bus_Matrix_Generator/verilog/src/cmsdk_ahb_bm_default_slave.v
project addfile ../AHB_BusMatrix/AHB_Bus_Matrix_Generator/verilog/src/cmsdk_ahb_bm_fixed_arb.v
project addfile ../AHB_BusMatrix/AHB_Bus_Matrix_Generator/verilog/src/cmsdk_ahb_bm_input_stage.v
project addfile ../AHB_BusMatrix/AHB_Bus_Matrix_Generator/verilog/src/cmsdk_ahb_bm_output_stage.v
project addfile ../AHB_BusMatrix/AHB_Bus_Matrix_Generator/verilog/src/cmsdk_ahb_bm_round_arb.v
project addfile ../AHB_BusMatrix/AHB_Bus_Matrix_Generator/verilog/src/cmsdk_ahb_bm_single_arb.v
project addfile ../AHB_BusMatrix/AHB_Bus_Matrix_Generator/verilog/src/cmsdk_ahb_bm_single_output_stage.v
project addfile ../AHB_BusMatrix/AHB_Bus_Matrix_Generator/verilog/src/cmsdk_ahb_busmatrix.v
project addfile ../AHB_BusMatrix/AHB_Bus_Matrix_Generator/verilog/src/cmsdk_ahb_busmatrix_lite.v
project addfile ../AHB_BusMatrix/AHB_Arbiter.v
project addfile ../AHB_BusMatrix/AHB_BusMatrix.v
project addfile ../AHB_BusMatrix/AHB_BusMatrix_default_slave.v
project addfile ../AHB_BusMatrix/AHB_BusMatrix_lite.v
project addfile ../AHB_BusMatrix/AHB_DecoderStageS0.v
project addfile ../AHB_BusMatrix/AHB_InputStage.v
project addfile ../AHB_BusMatrix/AHB_OutputStage.v
project addfile ../Peripherals/APB/APB_Bridge.v
project addfile ../Peripherals/APB/APB_decoder.v
project addfile ../Peripherals/APB/APB_Subsystem.v
project addfile ../Peripherals/APB/cmsdk_apb_slave_mux.v
project addfile ../Peripherals/Timer/ClkDiv.v
project addfile ../Peripherals/Timer/Timer.v
project addfile ../Peripherals/Timer/Timer_APB.v
project addfile ../Peripherals/UART/UART_Rx/UART_Rx_Counter.v
project addfile ../Peripherals/UART/UART_Rx/UART_Rx_Deserializer.v
project addfile ../Peripherals/UART/UART_Rx/UART_Rx_FSM.v
project addfile ../Peripherals/UART/UART_Rx/UART_Rx_ParChk.v
project addfile ../Peripherals/UART/UART_Rx/UART_Rx_Sampler.v
project addfile ../Peripherals/UART/UART_Rx/UART_Rx_StpChk.v
project addfile ../Peripherals/UART/UART_Rx/UART_Rx_StrtChk.v
project addfile ../Peripherals/UART/UART_Rx/UART_Rx_TOP.v
project addfile ../Peripherals/UART/UART_Tx/UART_Tx_FSM.v
project addfile ../Peripherals/UART/UART_Tx/UART_Tx_MUX.v
project addfile ../Peripherals/UART/UART_Tx/UART_Tx_ParCalc.v
project addfile ../Peripherals/UART/UART_Tx/UART_Tx_Serializer.v
project addfile ../Peripherals/UART/UART_Tx/UART_Tx_TOP.v
project addfile ../Peripherals/UART/Async_FIFO.v
project addfile ../Peripherals/UART/ClkDiv.v
project addfile ../Peripherals/UART/UART_APB.v
project addfile ../Peripherals/GPIO_Controller.v
project addfile ../RAMs/cmsdk_ahb_to_dsram.v
project addfile ../RAMs/cmsdk_ahb_to_isram.v
project addfile ../RAMs/cmsdk_fpga_dsram.v
project addfile ../RAMs/cmsdk_fpga_isram.v
project addfile ../RAMs/DATA_SRAM_TOP.v
project addfile ../RAMs/Instruction_SRAM_TOP.v
project addfile ../RV32I/AHB%20Wrapper/AHB%20Master.v
project addfile ../RV32I/Caches/DCache.v
project addfile ../RV32I/Caches/ICache.v
project addfile ../RV32I/Caches/Memory_Arbiter.v
project addfile ../RV32I/Caches/Sync_RAM.v
project addfile ../RV32I/Pipeline/ALU.v
project addfile ../RV32I/Pipeline/BranchLogic.v
project addfile ../RV32I/Pipeline/ControlUnit.v
project addfile ../RV32I/Pipeline/EX_MEM_Reg.v
project addfile ../RV32I/Pipeline/HazardUnit.v
project addfile ../RV32I/Pipeline/ID_EX_Reg.v
project addfile ../RV32I/Pipeline/IF_ID_Reg.v
project addfile ../RV32I/Pipeline/MEM_WB_Reg.v
project addfile ../RV32I/Pipeline/Mux-4to1.v
project addfile ../RV32I/Pipeline/Mux-8to1.v
project addfile ../RV32I/Pipeline/Mux_2to1.v
project addfile ../RV32I/Pipeline/PC.v
project addfile ../RV32I/Pipeline/PCPlus4Adder.v
project addfile ../RV32I/Pipeline/PCTargetAdder.v
project addfile ../RV32I/Pipeline/RegisterFile.v
project addfile ../RV32I/Pipeline/SignExtend.v
project addfile ../RV32I/Pipeline/Zicsr.v
project addfile ../RV32I/RV32I.v
project addfile ../System_Top.v

